### ISSUE TITLE
Illuminate\Session\Store is empty when setting "auth" middleware on routes in Plugin

### ISSUE THREAD

**Issue by DRogueRonin** [oneso/laravel-plugins#7]
**routes.php in Plugin**
```php
Route::get('plugin', [\App\Plugins\Admin\Http\Controllers\HomeController::class, 'index']);

Route::middleware(['auth'])->group( function () {
    Route::get('admin', [\App\Plugins\Admin\Http\Controllers\AdminController::class, 'index']);
});
```

**routes/web.php**
```php
Auth::routes();

Route::middleware(['auth'])->group( function () {
    Route::get('persons', [PersonController::class, 'index']);
});
```

When navigating to `/persons`, defined in the Laravel `routes/web.php`, it works as expected, the view is shown.
When navigating to `/plugin`, defined in the Plugin's `routes.php`, it works as expected, the view is shown.

But when navigating to `/admin`, defined in the Plugin's `routes.php`, it redirects back to `/home`, the default redirectTo target in the Authenticate Middleware.

This happens because

**/persons**

![Bildschirmfoto 2021-02-04 um 23 11 32](https://user-images.githubusercontent.com/16617893/106962775-eb1bcb80-673f-11eb-8ea8-3ea80f0e0a1c.png)

**/admin**

![Bildschirmfoto 2021-02-04 um 23 11 17](https://user-images.githubusercontent.com/16617893/106962769-e9ea9e80-673f-11eb-8184-487fd2f48c37.png)

the Session\Store is empty for some reason.

Here (https://github.com/laravel/framework/blob/e47ca2ac92559533d731a82077fcb068e781f266/src/Illuminate/Auth/AuthManager.php#L125) you can see the crucial line in the framework where the store is retrieved from `$this->app`.
My guess is that the `Application` instance at this point is somehow connected to the instance that is provided to the `PluginServiceProvider` in the `register` method, since it's there where every Plugin is booted.

But I don't know what to do with that information or how to debug further.
The Laravel Docs state that
> You should never attempt to register any event listeners, routes, or any other piece of functionality within the register method.
> https://laravel.com/docs/8.x/providers#writing-service-providers

I don't know whether that's the problem. But I also don't know what to do now to get the correct `$app` instance and the correct Store.

**Comment by oneso** [comment]
I'll try to look into the problem, although i do not maintain this project anymore.

**Comment by oneso** [comment]
Found the problem. Don't know if this is a problem for Laravel 5 as well. You need to add the `web` middleware around all routes. As you can see in the `Kernel.php` the `web` middleware group starts the session. Your plugin `routes.php` would look like this:
```
Route::middleware('web')->group(function () {
    Route::get('plugin', [\App\Plugins\Admin\Http\Controllers\HomeController::class, 'index']);

    Route::middleware(['auth'])->group(function () {
        Route::get('admin', [\App\Plugins\Admin\Http\Controllers\AdminController::class, 'index']);
    });
});
```

**Comment by DRogueRonin** [comment]
Awesome! Thanks!

I tried drawing inspiration from the `RouteServiceProvider` when testing different approaches, but didn't think of adding the `web` middleware with it. Kind of obvious now that I think of it, haha.
