### ISSUE TITLE
Load translations from within the plugin

### ISSUE THREAD

**Issue by DRogueRonin** [oneso/laravel-plugins#8]
I tried loading translations from within the Plugin's `boot()` method, but don't have access to the `TranslationServiceProvider` yet, since it is a deferred ServiceProvider, I think.
So `$this->app->translator` isn't loaded yet and can't be found.

Just for testing how to even load translations from custom paths I tried from a Controller
```php
app('translator')->load(app('laravel-plugins')->getPluginDirectory() . '/Test/lang', 'test', app()->getLocale());
```

and in the plugin I have a `lang/$locale/test.php` file with test data. `return ['test' => 'Test']`
Calling `__('test.test')` doesn't give me the translation though, it just returns they key, so the translations don't seem to get loaded. I tried different paths with the `load()` method on the translator, but nothing worked yet.

So one problem is how to access the `TranslationServiceProvider` and the other how to correctly load the translations then.
Maybe you got some insights on that?

**Comment by oneso** [comment]
There is a `loadTranslationsFrom` method in `Illuminate\Support\ServiceProvider` that shows you how to do it by using the `$this->app->afterResolving` method. Does this help you?

**Comment by dweipert-3138720606** [comment]
Yes! Thanks! That's the hint I needed!

I got it working with
```php
/**
 * Add a translations namespace for this plugin.
 * Eg: __("plugin:articles::{trans_path}")
 * 
 * @param string $path
 */
protected function enableTranslations($path = 'lang')
{
    $this->app->afterResolving('translator', function (Translator $translator) use ($path) {
        $translator->addNamespace(
            $this->getViewNamespace(), 
            $this->getPluginPath() . DIRECTORY_SEPARATOR . $path
        );
    });
}
```

**Comment by oneso** [comment]
Great! Feel free to make a PR.
